[package]
name = "async-io-unixstream-error"
version = "0.1.0"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
env_logger = "0.7"
async-io  = { git = "https://github.com/stjepang/async-io" }
futures-lite = "0.1"
async-std = "=1.5.0"